### ISSUE TITLE
No results showing up

### ISSUE THREAD

**Issue by scoobydoofus** [roest01/docker-speedtest-analyser#12]
EDIT:

Never mind! I just checked it and it’s working, I can see results in chart every hour! Not sure if it will store the results permanently but I can see how the connection was overnight which is what I wanted! 

——

Apologies if this isn't the right place to ask such a basic question but I can't seem to get this working using the Docker GUI on my Synology NAS box. I can access the web interface and see a chart but it doesn't have any data.

Your instructions say "Moint host volume onto /var/www/html/data/", and I'm not 100% certain I've done that correctly.

What I've done with other docker containers is create a folder called "Docker" and then created subfolders for the config files for all my various containers, and then set the mount path for each container as instructed in the readme.

So in this case, I have a folder inside my Docker folder for this container, and I set the mount path to /var/www/html/data/ but it doesn't seem to actually do anything, I don't see any files appear in the folder I specified.

I've attached the log from the Docker GUI, seems to be trying to do something every few mins, but I don't see any errors that help me to resolve it.

If I haven't mounted the host volume correctly, I'd be really grateful if you could give me some more detailed help with that. Sorry again if this is really basic stuff!

[Speedtest.csv.zip](https://github.com/roest01/docker-speedtest-analyser/files/2650253/Speedtest.csv.zip)

**Comment by roest01** [comment]
Hey @scoobydoofus,

I'm glad you got it running.
It sounds like you have mounted a volume into /var/www/html/data/ - by that the results are stored permanently and you can upgrade and modify the container. If you're not sure about that, just make a copy of the results.csv file as backup.  

Have fun :)
