### ISSUE TITLE
allow custom mini Server for cli

### ISSUE THREAD

**Issue by roest01** [roest01/docker-speedtest-analyser#16]
There are some optional arguments in `speedtest-cli` which might be relevant. 
Add option to extend the default speedtest command with custom options for example custom mini server.

**Comment by jrada** [comment]
It would be useful to be able to use the "--server" argument and specify a server ID ([https://www.speedtestserver.com/](https://www.speedtestserver.com/))...which seems to be possible through the SPEEDTEST_PARAMS variable, right?
I'd also like to be able to run speetdtest-cli with the "--share" argument and store the "result ID" for each measurement (into the CSV file). Then I would check results on speedtest.net ([https://www.speedtest.net/result/&lt;result_ID&gt;](https://www.speedtest.net/result/\&lt;result_ID&gt;)) manually...or even better the link for each measurement could be available directly in the analyser UI.

**Comment by roest01** [comment]
solved by merge of #17
