### ISSUE TITLE
CSV Timestamp Bug

### ISSUE THREAD

**Issue by xdtrammell** [roest01/docker-speedtest-analyser#22]
![image](https://user-images.githubusercontent.com/3378289/57352474-7616fe80-7133-11e9-99ba-c8ef62e78a56.png)

The timestamps in the CSV file are showing up as a decimal rather than a date.

**Comment by roest01** [comment]
Hey =)

Timestamp normally is an integer.  
I'm pretty sure the decimal value has to do with excel and is a formatting error only. 
Please do a screenshot within a text editor.

Does this bug affect inter Speedtest analyser interface in any way?

**Comment by Paytah232** [comment]
I'd like to reopen this as this bug definitely still exists.

![image](https://user-images.githubusercontent.com/44075588/61882938-cd5f8a80-af3c-11e9-913d-fce8b4dce63f.png)

It doesn't seem to affect the interface, but it's rather annoying when I want to use the csv data for other things and the timestamp is gibberish.

![image](https://user-images.githubusercontent.com/44075588/61883048-0bf54500-af3d-11e9-8cb0-029c9e3e75b9.png)
