### ISSUE TITLE
How do I know if it's working?

### ISSUE THREAD

**Issue by Paytah232** [roest01/docker-speedtest-analyser#23]
Not sure if this is the right way to contact you, but:

I'm running a Synology 718+ and have installed your docker image. I think I have correctly mounted the volume to access the csv file, as I see it in the folder.

However I seem to be having trouble accessing the web interface for it. Should I be setting a constant port for the interface on the 443 and 80 ports; do I only need to access one; which one?

Thanks in advance.

**Comment by roest01** [comment]
Hey, 
glad you got it running. I'm using both ports but KIS - only one is required.

![portmapping_synology](https://user-images.githubusercontent.com/2870718/57570966-2f155b80-7408-11e9-8971-de48475f505b.png)

After that the web interface is available within the local port:
http:// my-nas.local:32769
https:// my-nas.local:32768
