### ISSUE TITLE
I FIXED CSV TIMESTAMP BUG

### ISSUE THREAD

**Issue by Paytah232** [roest01/docker-speedtest-analyser#26]
I'd like to reopen this as this bug definitely still exists.

![image](https://user-images.githubusercontent.com/44075588/61882938-cd5f8a80-af3c-11e9-913d-fce8b4dce63f.png)

It doesn't seem to affect the interface, but it's rather annoying when I want to use the csv data for other things and the timestamp is gibberish.

![image](https://user-images.githubusercontent.com/44075588/61883048-0bf54500-af3d-11e9-8cb0-029c9e3e75b9.png)

_Originally posted by @Paytah232 in https://github.com/roest01/docker-speedtest-analyser/issues/22#issuecomment-515068795_

**Comment by Paytah232** [comment]
[speedtest.zip](https://github.com/roest01/docker-speedtest-analyser/files/3447233/speedtest.zip)

I fixed this bug while tinkering on my Synology NAS. The following steps are for a Synology NAS, but I'd imagine you can do the equivalent on your machine and it will work. @roest01 Feel free to merge this with the master branch if you think it's a good fix.

1. Download and Extract the speedtest.zip link. The file you're interested in is speedtest.py

2. In your NAS, find a location where you can set a volume to for this script (I put in near where I find results.csv), which in my case is /docker/Speedtest/Script. Copy speedtest.py to this location
![image](https://user-images.githubusercontent.com/44075588/62137398-3b36f800-b329-11e9-89d1-eff15e209c55.png)

3. In the docker container running this docker, go to the edit tab, and then volume. To be the same as mine enter the following as the mount path and then apply: /var/www/html/scripts
![image](https://user-images.githubusercontent.com/44075588/62137566-894bfb80-b329-11e9-8d86-2786df7da6be.png)
Ensure you have put the speedtest.py file in the specified mount location, or else your speedtest won't work!

4. While you're here, you need to add your timezone for this to work (I doubt it works without it but I didn't check). The link to these values can be found here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
For example, I am from Brisbane, Australia, so mine timezone is: Australia/Brisbane
Navigate to the Environment tab in the edit window and add a variable (TZ), with the your timezone as the value:
![image](https://user-images.githubusercontent.com/44075588/62138531-1e9bbf80-b32b-11e9-8b1a-b70d735d31fb.png)



5. Start the docker container, click the details tab, then terminal and then create. Click on the new bash tab and enter: pip install pytz
![image](https://user-images.githubusercontent.com/44075588/62138054-56eece00-b32a-11e9-98a1-af33b618ebfc.png)

6. Go and run a manual speedtest and check your results file. Hopefully you should see the correct time format, like my example below (comparing before and after the bug fix).
![image](https://user-images.githubusercontent.com/44075588/62138193-974e4c00-b32a-11e9-9cfc-20fa5fdb5b3f.png)

I hope this helps your speedtest work as well as mine does now!

**Comment by roest01** [comment]
Hey Paytah,
Thank you for this wonderful and good looking issue. 
What you did is easy to understand because of these screenshots.

Do not be angry with me - im not sure if this is a good solution.
The timestamp is a raw format. Its technically easy to process and unspecified in timezone and date format. What you see in your csv is a german format now. 
i like to keep it generic. My recommend solution would be to parse the timestamp with excel or google docs. A formula could be `=(A2-DATE(1970,1,1))*86400`. Just google "timestamp to date excel".

Can the interface still work with a date string? 
I mean the implementation is based on supposition that there is a timestamp not a date.

**Comment by Paytah232** [comment]
@roest01 You're right, the interface didn't work with the date string. I fixed this by recording the timestamp to the original results.csv file (as you initially did), but then I output a second readable_results.csv, that is in a human readable format, more suitable for excel or directly reading the csv file in a text editor. I will edit the link accordingly above and add the new script here as well. Works for me :)

![image](https://user-images.githubusercontent.com/44075588/62141554-1bef9900-b330-11e9-999e-97b7a83c19db.png)

Updated Script : 
[speedtestV2.zip](https://github.com/roest01/docker-speedtest-analyser/files/3447460/speedtestV2.zip)

**Comment by roest01** [comment]
another idea for you env is to output the readable format within a new cell **after** upload.
this should not compromise the interface but you have a single file only ;)

**Comment by Paytah232** [comment]
Done : [speedtestV3.zip](https://github.com/roest01/docker-speedtest-analyser/files/3447511/speedtestV3.zip)

![image](https://user-images.githubusercontent.com/44075588/62142652-0c714f80-b332-11e9-8edd-09ac26e5ee3f.png)

Can confirm interface still works as well. I will update the original post again.
![image](https://user-images.githubusercontent.com/44075588/62142734-3296ef80-b332-11e9-80d3-070d068113c4.png)
