### ISSUE TITLE
CRONJOB_ITERATION has no effect?

### ISSUE THREAD

**Issue by Paytah232** [roest01/docker-speedtest-analyser#27]
![image](https://user-images.githubusercontent.com/44075588/62181159-bb934280-b395-11e9-9406-a14501705494.png)

I followed the guide to set this to 30mins, but it still only seems to run every hour???

![image](https://user-images.githubusercontent.com/44075588/62181218-e67d9680-b395-11e9-8296-6cf04d62ad2a.png)

Any way to fix it or test the new interval? Perhaps it's passing the wrong variable name or just not considering it and just defaulting to 60mins @roest01

**Comment by roest01** [comment]
please see #20
