### ISSUE TITLE
Move Ping Results to secondary chart axis

### ISSUE THREAD

**Issue by PhilippeSch** [roest01/docker-speedtest-analyser#28]
Hi there

I really love your docker speedtest, it is just great!

Luckily I have a very fast internet connection with low latency. Therefore, I can hardly see the latency results (~6ms) in comparison to the full axis (~1000Mbit). So it would be great if you could move the ping results to a secondary axis ;). That would be amazing!

![Bildschirmfoto 2019-09-08 um 13 39 20](https://user-images.githubusercontent.com/37478575/64487750-6f61da80-d23e-11e9-94eb-911209209a80.png)

Furthermore, did you ever think of some smoothening? Especially for larger timeframes, it is hard to say anything about the long-time speed behaviour....

![Bildschirmfoto 2019-09-08 um 13 43 46](https://user-images.githubusercontent.com/37478575/64487776-c4055580-d23e-11e9-8d86-25a1c12edc7d.png)

Anyway, thanks a lot for your great work :)!!

**Comment by roest01** [comment]
Hey thank you for the nice feedback =) 

To put the ping on his own axis is a good idea. Will think about that. 
Meanwhile just a quick note. You can hide and show different axis by clicking on the depend legend. 
Try it and hide download + upload.

**Comment by PhilippeSch** [comment]
Wow thank you for the fast hint :). That actually solves the problem 👍, so I'll close the issue again ;).
![Bildschirmfoto 2019-09-08 um 14 25 48](https://user-images.githubusercontent.com/37478575/64488145-97ecd300-d244-11e9-897e-58d186636dda.png)
