### ISSUE TITLE
Docker Speedtest does not work anymore

### ISSUE THREAD

**Issue by stele99** [roest01/docker-speedtest-analyser#55]
With the latest release the docker speedtest does not work.
speedtest is not performed anymore. no automatic speedtests, no manual speedtest.

log when starting the image:
Starting run.sh
Starting Cronjob
Starting nginx
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/5.1/resty/core.lua'
	no file '/usr/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/common/resty/core.lua'
	no file '/usr/share/lua/common/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')

**Comment by stevietv** [comment]
having the same issue here.
also getting the following log entry everytime the cronjob should run:

`/bin/ash: /var/www/html/scripts/speedtestRunner.py: Permission denied`

**Comment by Bushwacker2020** [comment]
Echoing this issue.  I pulled the image with the "develop" tag and it still works.  Seem to be a lot of projects that are encountering issues with LauJIT.

**Comment by JacobOkanta** [comment]
Also having this issue was originally getting the `/bin/ash: /var/www/html/scripts/speedtestRunner.py: Permission denied` error. Tried removing and recreating the container and started getting the LuaJIT errors. While using the "develop" tag may work it should be noted that according to the Docker Hub that version was last updated 2 years ago.

**Comment by tuckshoprn** [comment]
I'm also having this issue.

Container log is:

Starting run.sh,
Starting Cronjob,
Starting nginx,
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html),
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:,
	no field package.preload['resty.core'],
	no file './resty/core.lua',
	no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua',
	no file '/usr/local/share/lua/5.1/resty/core.lua',
	no file '/usr/local/share/lua/5.1/resty/core/init.lua',
	no file '/usr/share/lua/5.1/resty/core.lua',
	no file '/usr/share/lua/5.1/resty/core/init.lua',
	no file '/usr/share/lua/common/resty/core.lua',
	no file '/usr/share/lua/common/resty/core/init.lua',
	no file './resty/core.so',
	no file '/usr/local/lib/lua/5.1/resty/core.so',
	no file '/usr/lib/lua/5.1/resty/core.so',
	no file '/usr/local/lib/lua/5.1/loadall.so',
	no file './resty.so',
	no file '/usr/local/lib/lua/5.1/resty.so',
	no file '/usr/lib/lua/5.1/resty.so',
	no file '/usr/local/lib/lua/5.1/loadall.so')

**Comment by fudge01010** [comment]
Been doing some testing, and coming to the same conclusion as @tuckshoprn - seems to be a permissions issue. Running the `latest` docker tag, and then doing `chmod 755 speedtestRunner.py` seems to partially fix it - I get speedtest results in the console when I click the 'start manual speedtest' button, with them being written to the .csv successfully.

Going to send a PR shortly :) but anyone else with the issue in the meantime, changing script to executable seems to fix it.

** Note: **
If you had any speedtests done and saved to your csv between what looks like #53 and #54, then no new results will appear on your graph, even though they are being recorded.

You will either need to remove the bad results from your csv (the timestamp is 1000x smaller than the others, easy to spot), or create a new file.

**Comment by stevietv** [comment]
thanks for doing the PR @fudge01010 - lets wait for it to get merged.
note: if you add fixed #55 to the PR description it should link PR and issue and allow both to be closed

**Comment by luandro** [comment]
Even with this fix I still get this error:

```
speedtest    | Traceback (most recent call last):
speedtest    |   File "/var/www/html/scripts/speedtestRunner.py", line 62, in <module>
speedtest    |     runSpeedtest()
speedtest    |   File "/var/www/html/scripts/speedtestRunner.py", line 25, in runSpeedtest
speedtest    |     s = Speedtest()
speedtest    |   File "/usr/lib/python2.7/site-packages/speedtest.py", line 1091, in __init__
speedtest    |     self.get_config()
speedtest    |   File "/usr/lib/python2.7/site-packages/speedtest.py", line 1123, in get_config
speedtest    |     raise ConfigRetrievalError(e)
speedtest    | speedtest.ConfigRetrievalError: <urlopen error [Errno -3] Try again>
```

Related at all, or should open another issue?

**Comment by jaxjexjox** [comment]
Ok I thought this was me and my results.csv was damaged or something.

Thanks guys.

**Comment by jaxjexjox** [comment]
Yeah the chmod change fixed stuff.

**Comment by jaxjexjox** [comment]
Did this get wrapped up?   I'm curious if I can update yet.

**Comment by stevietv** [comment]
not yet, still waiting for @roest01 to merge PR #57

**Comment by EVOTk** [comment]
Hello,
I have the same problems :(

Synology DS918+ / DSM 6.2.3

**Comment by tuckshoprn** [comment]
The latest release fixed this for me.  You may need to reset the csv file if previous versions have entered incorrectly formatted data.

**Comment by EVOTk** [comment]
Thank you for the answer.
It works now, but the error is still present on launch.
